name: cd

on: [ push, pull_request ]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 14 ]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Generate
        run: yarn generate

      - name: Copy Cname
        run: cp CNAME dist/CNAME

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SUPER_TOKEN }}
        with:
          source-directory: './dist'
          destination-github-username: 'neofoxindia'
          destination-repository-name: 'www.neofox.org'
          user-email: ashvinijangid@gmail.com
          target-branch: main

#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.SUPER_TOKEN }}
#          publish_dir: ./dist
